export const movies =[
    {
    movie_aid:1,
    movie_title: "transformers",
    movie_year: "2003",
    movie_duration: "1hr 50mins",
    movie_category: "International",
    movie_genre: "Action",
    movie_summary: "An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.",
    movie_cast: "Shia LaBeoufMegan FoxJosh Duhamel",
    movie_rating: "R",
    movie_image: "transformers.webp",
    movie_is_active: true,

},
    {
    movie_aid:2,
    movie_title: "Terminator 2: Judgment Day",
    movie_year: "2003",
    movie_duration: "1hr",
    movie_category: "International",
    movie_genre: "Action",
    movie_summary: "An ancient A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg. between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.",
    movie_cast: "Arnold SchwarzeneggerLinda HamiltonEdward Furlong",
    movie_rating: "R",
    movie_image: "terminator.jpg",
    movie_is_active: true,

},
    {
    movie_aid:3,
    movie_title: "John Wick",
    movie_year: "2014",
    movie_duration: "1h 41m",
    movie_category: "International",
    movie_genre: "Action,Crime",
    movie_summary: "John Wick is a former hitman grieving the loss of his true love. When his home is broken into, robbed, and his dog killed, he is forced to return to action to exact revenge.",
    movie_cast: "Keanu ReevesMichael NyqvistAlfie Allen",
    movie_rating: "R",
    movie_image: "johnwick.webp",
    movie_is_active: true,

},
    {
    movie_aid:4,
    movie_title: "The Matrix Reloaded",
    movie_year: "2003",
    movie_duration: "2h 18m",
    movie_category: "International",
    movie_genre: "Action",
    movie_summary: "Freedom fighters Neo, Trinity and Morpheus continue to lead the revolt against the Machine Army, unleashing their arsenal of extraordinary skills and weaponry against the systematic forces of repression and exploitation.",
    movie_cast: "Keanu ReevesLaurence FishburneCarrie-Anne Moss",
    movie_rating: "R",
    movie_image: "matrix.jpg",
    movie_is_active: true,

},
    {
    movie_aid:5,
    movie_title: "Deadpool & Wolverine",
    movie_year: "2024",
    movie_duration: "2h 8m",
    movie_category: "International",
    movie_genre: "Action",
    movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
    movie_cast: "Ryan ReynoldsHugh JackmanEmma Corrin",
    movie_rating: "R",
    movie_image: "wolverine.jpg",
    movie_is_active: true,

},
    {
    movie_aid:6,
    movie_title: "Avengers: Age of Ultron",
    movie_year: "2015",
    movie_duration: "2h 21m",
    movie_category: "International",
    movie_genre: "Action",
    movie_summary: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
    movie_cast: "Robert Downey Jr.Chris EvansMark Ruffalo",
    movie_rating: "PG-13",
    movie_image: "avengers.jpg",
    movie_is_active: true,

},
    {
    movie_aid:7,
    movie_title: "Rick and Morty: The Anime",
    movie_year: "2024",
    movie_duration: "2h 21m",
    movie_category: "Anime",
    movie_genre: "TV Series",
    movie_summary: "An anime series in 10 episodes, based on Rick and Morty.",
    movie_cast: "Yôhei TadanoKeisuke ChibaAkiha Matsui",
    movie_rating: "TV-14",
    movie_image: "rickandmorty.jpg",
    movie_is_active: true,

},
    {
    movie_aid:8,
    movie_title: "Spirited Away",
    movie_year: "2001",
    movie_duration: "2h 4m",
    movie_category: "Anime",
    movie_genre: "TV Series",
    movie_summary: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.",
    movie_cast: "Daveigh ChaseSuzanne PleshetteMiyu Irino",
    movie_rating: "PG",
    movie_image: "spirited away.jpg",
    movie_is_active: true,

},
    {
    movie_aid:9,
    movie_title: "Your Name.",
    movie_year: "2016",
    movie_duration: "1h 46m",
    movie_category: "Anime",
    movie_genre: "TV Series",
    movie_summary: "Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.",
    movie_cast: "Ryunosuke KamikiMone KamishiraishiRyo Narita",
    movie_rating: "PG",
    movie_image: "yourname.jpg",
    movie_is_active: true,

},
];